use iced::widget::{
    button, column, container, pick_list, row, rule, scrollable, text, text_editor, text_input,
    toggler, tooltip, Space,
};
use iced::{Element, Font, Length};

use crate::theme::{self, ThemeColors};
use crate::{AnisotropyLevel, DxvkConfig, DxvkField, Message, PresentInterval, TriState};

// ---------------------------------------------------------------------------
// Config generator (pure function — no Iced dependency)
// ---------------------------------------------------------------------------

pub fn generate_conf(cfg: &DxvkConfig) -> String {
    let mut s = String::with_capacity(1024);

    s.push_str("# dxvk.conf — generated by Wuddle\n");
    s.push_str("# Turtle WoW D3D9 configuration\n");

    // --- Performance & Latency ---
    s.push_str("\n############################\n");
    s.push_str("# Performance & Latency\n");
    s.push_str("############################\n\n");

    let fps: u32 = cfg.max_frame_rate.trim().parse().unwrap_or(0);
    if fps > 0 {
        s.push_str("# Cap the frame rate. Values above ~245 can cause physics/timer issues in vanilla WoW.\n");
        s.push_str(&format!("d3d9.maxFrameRate = {}\n", fps));
    } else {
        s.push_str("# d3d9.maxFrameRate = 0  # Unlimited. A cap of 240 or less is recommended.\n");
    }

    s.push('\n');
    let latency: u32 = cfg.max_frame_latency.trim().parse().unwrap_or(1).clamp(1, 16);
    s.push_str("# Frames the GPU may buffer ahead. Fewer frames = lower input latency (1 is recommended).\n");
    s.push_str(&format!("d3d9.maxFrameLatency = {}\n", latency));

    match cfg.latency_sleep {
        TriState::Auto => {} // DXVK default — omit
        TriState::True => {
            s.push_str("\n# Enable NVAPI/Reflex latency sleep for reduced input latency on NVIDIA GPUs.\n");
            s.push_str("dxvk.latencySleep = True\n");
        }
        TriState::False => {
            s.push_str("\n# Disable NVAPI/Reflex latency sleep.\n");
            s.push_str("dxvk.latencySleep = False\n");
        }
    }

    // --- Async Shader Compilation ---
    s.push_str("\n############################\n");
    s.push_str("# Async Shader Compilation\n");
    s.push_str("############################\n\n");

    if cfg.enable_async {
        s.push_str("# Enable asynchronous shader compilation — the primary fix for D3D9 stutter in WoW.\n");
        s.push_str("# Requires the gplasync/async fork of DXVK. Has no effect on vanilla DXVK builds.\n");
        s.push_str("dxvk.enableAsync = true\n");
    } else {
        s.push_str("# dxvk.enableAsync = true  # Async disabled; enable for gplasync builds.\n");
    }

    // --- Shader Compilation ---
    s.push_str("\n############################\n");
    s.push_str("# Shader Compilation\n");
    s.push_str("############################\n\n");

    let threads: u32 = cfg.num_compiler_threads.trim().parse().unwrap_or(0);
    if threads > 0 {
        s.push_str("# Number of background threads used to compile graphics pipelines (0 = all available cores).\n");
        s.push_str(&format!("dxvk.numCompilerThreads = {}\n", threads));
        s.push('\n');
    }

    match cfg.enable_gpl {
        TriState::Auto => {} // DXVK default — omit
        TriState::True => {
            s.push_str("# Use the Graphics Pipeline Library extension to reduce shader compile stutter.\n");
            s.push_str("# WARNING: True causes known rendering bugs in Turtle WoW — leave at Auto.\n");
            s.push_str("dxvk.enableGraphicsPipelineLibrary = True\n");
            s.push('\n');
        }
        TriState::False => {
            s.push_str("# Fully disable the Graphics Pipeline Library fast-path.\n");
            s.push_str("dxvk.enableGraphicsPipelineLibrary = False\n");
            s.push('\n');
        }
    }

    match cfg.track_pipeline_lifetime {
        TriState::Auto => {} // DXVK default — omit
        TriState::True => {
            s.push_str("# Track pipeline lifetimes and free those no longer in use to reduce VRAM usage.\n");
            s.push_str("dxvk.trackPipelineLifetime = True\n");
            s.push('\n');
        }
        TriState::False => {
            s.push_str("# Disable pipeline lifetime tracking.\n");
            s.push_str("dxvk.trackPipelineLifetime = False\n");
            s.push('\n');
        }
    }

    // --- Display ---
    s.push_str("\n############################\n");
    s.push_str("# Display\n");
    s.push_str("############################\n\n");

    if cfg.enable_dialog_mode {
        s.push_str("# Run as a borderless-fullscreen window — improves alt-tab and multi-monitor behaviour.\n");
        s.push_str("d3d9.enableDialogMode = True\n");
        s.push('\n');
    }

    if !cfg.dpi_aware {
        s.push_str("# Disable DXVK's DPI awareness call — required when VanillaFixes or Wine already handle it.\n");
        s.push_str("d3d9.dpiAware = False\n");
        s.push('\n');
    }

    match cfg.present_interval {
        PresentInterval::Default => {} // -1: do not override, omit
        PresentInterval::NoSync => {
            s.push_str("# Force VSync off regardless of in-game setting (tearing may occur).\n");
            s.push_str("d3d9.presentInterval = 0\n");
            s.push('\n');
        }
        PresentInterval::Vsync => {
            s.push_str("# Force VSync on regardless of in-game setting (adds ~1 frame of latency).\n");
            s.push_str("d3d9.presentInterval = 1\n");
            s.push('\n');
        }
        PresentInterval::Half => {
            s.push_str("# Force half-rate VSync — limits to half the monitor refresh rate (e.g. 30 fps on 60 Hz).\n");
            s.push_str("d3d9.presentInterval = 2\n");
            s.push('\n');
        }
    }

    match cfg.tear_free {
        TriState::Auto => {} // DXVK default — omit
        TriState::True => {
            s.push_str("# Prevent screen tearing without the full input-latency cost of VSync.\n");
            s.push_str("dxvk.tearFree = True\n");
            s.push('\n');
        }
        TriState::False => {
            s.push_str("# Allow tearing (disables tear-free compositing entirely).\n");
            s.push_str("dxvk.tearFree = False\n");
            s.push('\n');
        }
    }

    // --- Image Quality ---
    s.push_str("\n############################\n");
    s.push_str("# Image Quality\n");
    s.push_str("############################\n\n");

    match cfg.sampler_anisotropy {
        AnisotropyLevel::NoOverride => {} // -1: let game/driver decide, omit
        AnisotropyLevel::Off => {
            s.push_str("# Disable anisotropic filtering for all samplers.\n");
            s.push_str("d3d9.samplerAnisotropy = 0\n");
            s.push('\n');
        }
        AnisotropyLevel::X2 => {
            s.push_str("# Force 2x anisotropic filtering — sharpens textures viewed at shallow angles.\n");
            s.push_str("d3d9.samplerAnisotropy = 2\n");
            s.push('\n');
        }
        AnisotropyLevel::X4 => {
            s.push_str("# Force 4x anisotropic filtering — noticeably sharper ground textures.\n");
            s.push_str("d3d9.samplerAnisotropy = 4\n");
            s.push('\n');
        }
        AnisotropyLevel::X8 => {
            s.push_str("# Force 8x anisotropic filtering — high quality, minimal performance impact.\n");
            s.push_str("d3d9.samplerAnisotropy = 8\n");
            s.push('\n');
        }
        AnisotropyLevel::X16 => {
            s.push_str("# Force 16x anisotropic filtering — maximum quality, negligible performance cost on modern GPUs.\n");
            s.push_str("d3d9.samplerAnisotropy = 16\n");
            s.push('\n');
        }
    }

    if cfg.clamp_negative_lod_bias {
        s.push_str("# Clamp negative mipmap LOD bias to zero — prevents over-sharpening that causes terrain shimmer.\n");
        s.push_str("d3d9.clampNegativeLodBias = True\n");
        s.push('\n');
    }

    // --- D3D9 Misc ---
    if cfg.defer_surface_creation || cfg.lenient_clear {
        s.push_str("\n############################\n");
        s.push_str("# D3D9 Misc\n");
        s.push_str("############################\n\n");

        if cfg.defer_surface_creation {
            s.push_str("# Defer Vulkan surface creation until the first Present call — can fix startup crashes.\n");
            s.push_str("d3d9.deferSurfaceCreation = True\n");
            s.push('\n');
        }
        if cfg.lenient_clear {
            s.push_str("# Use a fast-path clear when the rect nearly fills the render target — minor perf gain.\n");
            s.push_str("d3d9.lenientClear = True\n");
            s.push('\n');
        }
    }

    // --- Logging & HUD ---
    if !cfg.log_path.is_empty() || !cfg.hud.is_empty() {
        s.push_str("\n############################\n");
        s.push_str("# Logging & HUD\n");
        s.push_str("############################\n\n");

        if !cfg.log_path.is_empty() {
            s.push_str("# Directory for dxvk.log. \".\" = same folder as the game executable. Empty = no log file.\n");
            s.push_str(&format!("dxvk.logPath = {}\n", cfg.log_path.trim()));
            s.push('\n');
        }
        if !cfg.hud.is_empty() {
            s.push_str("# On-screen performance overlay. Comma-separate values: fps, memory, devinfo, pipelines.\n");
            s.push_str(&format!("dxvk.hud = {}\n", cfg.hud.trim()));
        }
    }

    // Tidy trailing whitespace
    let trimmed = s.trim_end().to_string();
    format!("{}\n", trimmed)
}

// ---------------------------------------------------------------------------
// Display impls for pick_list support
// ---------------------------------------------------------------------------

impl std::fmt::Display for TriState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TriState::Auto => write!(f, "Auto"),
            TriState::True => write!(f, "True"),
            TriState::False => write!(f, "False"),
        }
    }
}

impl std::fmt::Display for PresentInterval {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PresentInterval::Default => write!(f, "Don't override"),
            PresentInterval::NoSync => write!(f, "No VSync (0)"),
            PresentInterval::Vsync => write!(f, "VSync (1)"),
            PresentInterval::Half => write!(f, "Half refresh (2)"),
        }
    }
}

impl std::fmt::Display for AnisotropyLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AnisotropyLevel::NoOverride => write!(f, "No override"),
            AnisotropyLevel::Off => write!(f, "Off (0\u{00D7})"),
            AnisotropyLevel::X2 => write!(f, "2\u{00D7}"),
            AnisotropyLevel::X4 => write!(f, "4\u{00D7}"),
            AnisotropyLevel::X8 => write!(f, "8\u{00D7}"),
            AnisotropyLevel::X16 => write!(f, "16\u{00D7}"),
        }
    }
}

// ---------------------------------------------------------------------------
// Syntax highlighter for .conf preview (line-level coloring)
// ---------------------------------------------------------------------------
//
// Settings = [comment_color, key_color, muted_color, text_color]
// Highlights lines: `#` → gray comment; `key = value` → key+muted+text; other → default.

pub struct ConfHighlighter {
    comment_color: iced::Color,
    key_color: iced::Color,
    muted_color: iced::Color,
    text_color: iced::Color,
    current_line: usize,
}

impl iced::advanced::text::Highlighter for ConfHighlighter {
    type Settings = [iced::Color; 4];
    type Highlight = Option<iced::Color>;
    type Iterator<'a> = std::vec::IntoIter<(std::ops::Range<usize>, Option<iced::Color>)>;

    fn new(s: &[iced::Color; 4]) -> Self {
        Self {
            comment_color: s[0],
            key_color: s[1],
            muted_color: s[2],
            text_color: s[3],
            current_line: 0,
        }
    }

    fn update(&mut self, s: &[iced::Color; 4]) {
        self.comment_color = s[0];
        self.key_color = s[1];
        self.muted_color = s[2];
        self.text_color = s[3];
    }

    fn change_line(&mut self, line: usize) {
        self.current_line = line;
    }

    fn highlight_line(&mut self, line: &str) -> Self::Iterator<'_> {
        let len = line.len();
        if line.starts_with('#') {
            // Every comment/divider line → uniform comment color
            vec![(0..len, Some(self.comment_color))].into_iter()
        } else if let Some(eq) = line.find(" = ") {
            // key = value → three colored spans
            vec![
                (0..eq, Some(self.key_color)),
                (eq..eq + 3, Some(self.muted_color)),
                (eq + 3..len, Some(self.text_color)),
            ]
            .into_iter()
        } else {
            vec![(0..len, None)].into_iter()
        }
    }

    fn current_line(&self) -> usize {
        self.current_line
    }
}

fn conf_highlight_format(
    h: &Option<iced::Color>,
    _theme: &iced::Theme,
) -> iced::advanced::text::highlighter::Format<Font> {
    iced::advanced::text::highlighter::Format { color: *h, font: None }
}

// ---------------------------------------------------------------------------
// View
// ---------------------------------------------------------------------------

pub fn view<'a>(
    cfg: &'a DxvkConfig,
    wow_dir: &str,
    show_preview: bool,
    preview_content: &'a iced::widget::text_editor::Content,
    colors: &ThemeColors,
) -> Element<'a, Message> {
    let c = *colors;
    let has_wow_dir = !wow_dir.is_empty();
    let conf_text = generate_conf(cfg);

    // ---- Title row ----
    let title_row = row![
        column![
            text("DXVK Configuration").size(18).color(c.title),
            text("Generate a dxvk.conf for Turtle WoW (D3D9 only — no dxgi.* options)")
                .size(13)
                .color(c.muted),
        ]
        .spacing(2),
        Space::new().width(Length::Fill),
        crate::close_button(&c),
    ]
    .align_y(iced::Alignment::Center);

    // Comment color: neutral cool gray (readable on all themes)
    let comment_gray = iced::Color::from_rgb(0.52, 0.56, 0.62);

    // ---- Body ----
    let body: Element<Message> = if show_preview {
        // Selectable, syntax-highlighted conf preview using text_editor (read-only)
        text_editor(preview_content)
            .on_action(Message::DxvkPreviewEditorAction)
            .font(Font::MONOSPACE)
            .size(13)
            .height(Length::Fill)
            .padding(16)
            .highlight_with::<ConfHighlighter>(
                [comment_gray, c.link, c.muted, c.text],
                conf_highlight_format,
            )
            .style(move |t, s| theme::log_editor_style(&c)(t, s))
            .into()
    } else {
        // Full-width scrollable settings cards
        scrollable(
            column![
                section_card(
                    "Performance & Latency",
                    column![
                        num_row_tip(
                            "Max Frame Rate",
                            "Limits the frame rate (FPS). 0 = Unlimited, Recommended: Match monitor\u{2019}s refresh rate for energy savings, or set a custom limit up to 240 FPS*",
                            "* Frame rates above 240 may increase the chances of weird behavior such as invisible Player & NPC models in some situations. This issue can still occur below 240 FPS, but is more likely to occur at higher frame rates.",
                            &cfg.max_frame_rate,
                            |s| Message::SetDxvkField(DxvkField::MaxFrameRate(s)),
                            &c,
                        ),
                        num_row(
                            "Max Frame Latency",
                            "How many frames the GPU may buffer ahead (1-16). Fewer frames means lower input latency. 1 is recommended for the most responsive feel.",
                            &cfg.max_frame_latency,
                            |s| Message::SetDxvkField(DxvkField::MaxFrameLatency(s)),
                            &c,
                        ),
                        tristate_row(
                            "Latency Sleep (NVAPI / Reflex)",
                            "Enables NVIDIA Reflex / NVAPI latency-sleep to reduce input latency on NVIDIA GPUs. Auto detects support at runtime and enables it automatically.",
                            cfg.latency_sleep.clone(),
                            |v| Message::SetDxvkField(DxvkField::LatencySleep(v)),
                            &c,
                        ),
                    ]
                    .spacing(16),
                    &c,
                ),
                section_card(
                    "Async Shader Compilation",
                    column![
                        check_row_note(
                            "Enable Async (dxvk.enableAsync)",
                            "THE primary fix for D3D9 shader stutter in WoW. Compiles shaders asynchronously so the game never hitches waiting for compilation. Requires the gplasync fork of DXVK — has no effect on vanilla DXVK builds.",
                            "May cause incorrectly rendered 2D portrait images on UnitFrames. Not an issue if you use 3D, animated, or custom portrait addons.",
                            cfg.enable_async,
                            |b| Message::SetDxvkField(DxvkField::EnableAsync(b)),
                            &c,
                        ),
                        num_row(
                            "Compiler Threads",
                            "Number of background threads dedicated to compiling graphics pipelines. 0 = use all available CPU cores. Reducing this can free cores for the game but may increase compile stutter.",
                            &cfg.num_compiler_threads,
                            |s| Message::SetDxvkField(DxvkField::NumCompilerThreads(s)),
                            &c,
                        ),
                        tristate_row_warn(
                            "Graphics Pipeline Library (GPL)",
                            "Uses the Vulkan GPL extension to pre-compile partial pipelines and reduce stutter. WARNING: setting True causes known rendering bugs in Turtle WoW — leave at Auto.",
                            cfg.enable_gpl.clone(),
                            |v| Message::SetDxvkField(DxvkField::EnableGpl(v)),
                            &c,
                        ),
                        tristate_row(
                            "Track Pipeline Lifetime",
                            "Tracks how long each pipeline has been in use and frees pipelines that are no longer referenced. Reduces long-session VRAM consumption at the cost of minor bookkeeping overhead.",
                            cfg.track_pipeline_lifetime.clone(),
                            |v| Message::SetDxvkField(DxvkField::TrackPipelineLifetime(v)),
                            &c,
                        ),
                    ]
                    .spacing(16),
                    &c,
                ),
                section_card(
                    "Display",
                    column![
                        check_row(
                            "Borderless Fullscreen (Dialog Mode)",
                            "Enabling this setting will make DXVK run in Borderless Windowed Mode. Enable for a much better alt-tab experience. Most users will want this setting to be ON.",
                            cfg.enable_dialog_mode,
                            |b| Message::SetDxvkField(DxvkField::EnableDialogMode(b)),
                            &c,
                        ),
                        check_row(
                            "DPI Aware",
                            "Lets DXVK call SetProcessDPIAware. Disable this when VanillaFixes or Wine already make the process DPI-aware, to avoid double-scaling artifacts.",
                            cfg.dpi_aware,
                            |b| Message::SetDxvkField(DxvkField::DpiAware(b)),
                            &c,
                        ),
                        pick_row(
                            "VSync / Present Interval",
                            "Override the VSync setting at the DXVK layer. Don\u{2019}t override: honours whatever the game requests. No VSync (0): forces VSync off, tearing may occur. VSync (1): forces VSync on, adds ~1 frame of latency. Half refresh (2): limits to half the monitor refresh rate (e.g. 30 fps on a 60 Hz display).",
                            &[
                                PresentInterval::Default,
                                PresentInterval::NoSync,
                                PresentInterval::Vsync,
                                PresentInterval::Half,
                            ][..],
                            cfg.present_interval.clone(),
                            |v| Message::SetDxvkField(DxvkField::PresentInterval(v)),
                            &c,
                        ),
                        tristate_row(
                            "Tear-Free",
                            "Inserts a compositor-level tear-free pass to prevent screen tearing without incurring the full ~1-frame input latency of VSync. Requires a compatible compositor.",
                            cfg.tear_free.clone(),
                            |v| Message::SetDxvkField(DxvkField::TearFree(v)),
                            &c,
                        ),
                    ]
                    .spacing(16),
                    &c,
                ),
                section_card(
                    "Image Quality",
                    column![
                        pick_row(
                            "Anisotropic Filtering",
                            "Override anisotropic filtering for all texture samplers. Improves texture sharpness on surfaces viewed at shallow angles (terrain, roads). 16x is recommended — negligible performance cost on modern GPUs.",
                            &[
                                AnisotropyLevel::NoOverride,
                                AnisotropyLevel::Off,
                                AnisotropyLevel::X2,
                                AnisotropyLevel::X4,
                                AnisotropyLevel::X8,
                                AnisotropyLevel::X16,
                            ][..],
                            cfg.sampler_anisotropy.clone(),
                            |v| Message::SetDxvkField(DxvkField::SamplerAnisotropy(v)),
                            &c,
                        ),
                        check_row(
                            "Clamp Negative LOD Bias",
                            "Clamps negative mipmap LOD bias values to zero. Prevents the over-sharpening that causes visible terrain shimmer and texture flickering at a distance in WoW.",
                            cfg.clamp_negative_lod_bias,
                            |b| Message::SetDxvkField(DxvkField::ClampNegativeLodBias(b)),
                            &c,
                        ),
                    ]
                    .spacing(16),
                    &c,
                ),
                section_card(
                    "D3D9 Misc",
                    column![
                        check_row(
                            "Defer Surface Creation",
                            "Delays Vulkan swapchain surface creation until the first Present call instead of at device creation. Can fix startup crashes or black screens on some hardware/driver combos.",
                            cfg.defer_surface_creation,
                            |b| Message::SetDxvkField(DxvkField::DeferSurfaceCreation(b)),
                            &c,
                        ),
                        check_row(
                            "Lenient Clear",
                            "Uses a fast-path clear when the scissor rectangle covers nearly the entire render target. Provides a small performance gain with no visual difference in WoW.",
                            cfg.lenient_clear,
                            |b| Message::SetDxvkField(DxvkField::LenientClear(b)),
                            &c,
                        ),
                    ]
                    .spacing(16),
                    &c,
                ),
                section_card(
                    "Logging & HUD",
                    column![
                        input_row(
                            "Log Path",
                            "Directory where dxvk.log is written. Use \".\" to write it next to the game executable. Leave empty to disable DXVK file logging (errors still go to stderr).",
                            &cfg.log_path,
                            |s| Message::SetDxvkField(DxvkField::LogPath(s)),
                            &c,
                        ),
                        hud_row(&cfg.hud, &c),
                    ]
                    .spacing(16),
                    &c,
                ),
            ]
            .spacing(10)
            .padding(iced::Padding {
                top: 0.0,
                right: 10.0,
                bottom: 4.0,
                left: 0.0,
            }),
        )
        .height(Length::Fill)
        .direction(theme::vscroll())
        .style(move |t, s| theme::scrollable_style(&c)(t, s))
        .into()
    };

    // ---- Footer ----
    let c2 = c;
    let preview_toggle_btn = if show_preview {
        button(text("\u{2190} Settings").size(13))
            .on_press(Message::ToggleDxvkPreview)
            .padding([7, 16])
            .style(move |_t, status| match status {
                button::Status::Hovered => theme::tab_button_hovered_style(&c2),
                _ => theme::tab_button_style(&c2),
            })
    } else {
        let icon_color = c2.text;
        let file_icon = iced::widget::svg(
            iced::widget::svg::Handle::from_memory(
                include_bytes!("../../icons/file.svg").to_vec(),
            ),
        )
        .width(14)
        .height(14)
        .style(move |_t, _s| iced::widget::svg::Style {
            color: Some(icon_color),
        });
        let btn_content = row![file_icon, text("File Preview").size(13)]
            .spacing(6)
            .align_y(iced::Alignment::Center);
        button(btn_content)
            .on_press(Message::ToggleDxvkPreview)
            .padding([7, 16])
            .style(move |_t, status| match status {
                button::Status::Hovered => theme::tab_button_hovered_style(&c2),
                _ => theme::tab_button_style(&c2),
            })
    };

    let c3 = c;
    let copy_btn = button(text("Copy to clipboard").size(13))
        .on_press(Message::CopyToClipboard(conf_text))
        .padding([7, 16])
        .style(move |_t, status| match status {
            button::Status::Hovered => theme::tab_button_hovered_style(&c3),
            _ => theme::tab_button_style(&c3),
        });

    let save_btn = {
        let c4 = c;
        let save_label = if has_wow_dir {
            "Save to WoW directory"
        } else {
            "Save (no WoW dir set)"
        };
        let b = button(text(save_label).size(13))
            .padding([7, 16])
            .style(move |_t, _s| {
                if has_wow_dir {
                    theme::tab_button_active_style(&c4)
                } else {
                    let mut s = theme::tab_button_style(&c4);
                    s.text_color = iced::Color { a: 0.4, ..c4.text };
                    s
                }
            });
        if has_wow_dir {
            b.on_press(Message::SaveDxvkConfig)
        } else {
            b
        }
    };

    let footer = row![
        preview_toggle_btn,
        Space::new().width(Length::Fill),
        copy_btn,
        save_btn,
    ]
    .spacing(8)
    .align_y(iced::Alignment::Center);

    // ---- Full layout ----
    column![
        title_row,
        rule::horizontal(1).style(move |_t| theme::update_line_style(&c)),
        body,
        rule::horizontal(1).style(move |_t| theme::update_line_style(&c)),
        footer,
    ]
    .spacing(10)
    .height(Length::Fill)
    .into()
}

// ---------------------------------------------------------------------------
// Row helpers
// ---------------------------------------------------------------------------

/// Section card wrapping a group of settings rows.
fn section_card<'a>(
    title: &str,
    content: impl Into<Element<'a, Message>>,
    colors: &ThemeColors,
) -> Element<'a, Message> {
    let c = *colors;
    container(
        container(
            column![
                text(String::from(title)).size(18).color(c.title),
                rule::horizontal(1).style(move |_t| theme::update_line_style(&c)),
                content.into(),
            ]
            .spacing(8),
        )
        .padding(14),
    )
    .width(Length::Fill)
    .style(move |_t| theme::card_style(&c))
    .into()
}

/// Label + short description — shown below the label in every row.
fn label_desc<'a>(label: &str, desc: &str, colors: &ThemeColors) -> Element<'a, Message> {
    column![
        text(String::from(label)).size(15).color(colors.text),
        text(String::from(desc)).size(14).color(colors.muted),
    ]
    .spacing(1)
    .width(Length::FillPortion(7))
    .into()
}

/// Wraps `content` in a tooltip that shows `tip` on hover.
fn with_tip<'a>(
    content: impl Into<Element<'a, Message>>,
    tip: &str,
    c: ThemeColors,
) -> Element<'a, Message> {
    let tip_box = container(text(String::from(tip)).size(12).color(c.text))
        .max_width(360)
        .padding([6, 10])
        .style(move |_t| theme::tooltip_style(&c));
    container(tooltip(content, tip_box, tooltip::Position::Bottom))
        .width(Length::Fill)
        .into()
}

/// Toggler row: label + description on the left, toggler on the right.
fn check_row<'a, F>(
    label: &str,
    desc: &str,
    value: bool,
    on_toggle: F,
    colors: &ThemeColors,
) -> Element<'a, Message>
where
    F: 'a + Fn(bool) -> Message,
{
    let c = *colors;
    let inner = row![
        label_desc(label, desc, colors),
        Space::new().width(Length::FillPortion(3)),
        toggler(value).on_toggle(on_toggle).size(20),
    ]
    .spacing(10)
    .align_y(iced::Alignment::Center);
    with_tip(inner, desc, c)
}

/// Toggler row with an extra orange warning note below the description.
fn check_row_note<'a, F>(
    label: &str,
    desc: &str,
    note: &str,
    value: bool,
    on_toggle: F,
    colors: &ThemeColors,
) -> Element<'a, Message>
where
    F: 'a + Fn(bool) -> Message,
{
    let c = *colors;
    let label_col: Element<Message> = column![
        text(String::from(label)).size(15).color(c.text),
        text(String::from(desc)).size(14).color(c.muted),
        row![
            text("\u{26A0} ").size(13).color(c.warn),
            text(String::from(note)).size(13).color(c.warn),
        ]
        .align_y(iced::Alignment::Start),
    ]
    .spacing(2)
    .width(Length::FillPortion(7))
    .into();

    let inner = row![
        label_col,
        Space::new().width(Length::FillPortion(3)),
        toggler(value).on_toggle(on_toggle).size(20),
    ]
    .spacing(10)
    .align_y(iced::Alignment::Center);
    with_tip(inner, desc, c)
}

/// Number text-input row.
fn num_row<'a, F>(
    label: &str,
    desc: &str,
    value: &str,
    on_input: F,
    colors: &ThemeColors,
) -> Element<'a, Message>
where
    F: 'a + Fn(String) -> Message,
{
    let c = *colors;
    let inner = row![
        label_desc(label, desc, colors),
        Space::new().width(Length::FillPortion(3)),
        text_input("", value)
            .on_input(on_input)
            .width(80)
            .padding([5, 8]),
    ]
    .spacing(10)
    .align_y(iced::Alignment::Center);
    with_tip(inner, desc, c)
}

/// Number text-input row with a separate tooltip text (different from the inline description).
fn num_row_tip<'a, F>(
    label: &str,
    desc: &str,
    tip: &str,
    value: &str,
    on_input: F,
    colors: &ThemeColors,
) -> Element<'a, Message>
where
    F: 'a + Fn(String) -> Message,
{
    let c = *colors;
    let inner = row![
        label_desc(label, desc, colors),
        Space::new().width(Length::FillPortion(3)),
        text_input("", value)
            .on_input(on_input)
            .width(80)
            .padding([5, 8]),
    ]
    .spacing(10)
    .align_y(iced::Alignment::Center);
    with_tip(inner, tip, c)
}

/// Text-input row (for string fields like logPath / hud).
fn input_row<'a, F>(
    label: &str,
    desc: &str,
    value: &str,
    on_input: F,
    colors: &ThemeColors,
) -> Element<'a, Message>
where
    F: 'a + Fn(String) -> Message,
{
    let c = *colors;
    let inner = row![
        label_desc(label, desc, colors),
        Space::new().width(Length::FillPortion(3)),
        text_input("", value)
            .on_input(on_input)
            .width(120)
            .padding([5, 8]),
    ]
    .spacing(10)
    .align_y(iced::Alignment::Center);
    with_tip(inner, desc, c)
}

/// TriState pick_list row (Auto / True / False).
fn tristate_row<'a, F>(
    label: &str,
    desc: &str,
    value: TriState,
    on_select: F,
    colors: &ThemeColors,
) -> Element<'a, Message>
where
    F: 'a + Fn(TriState) -> Message,
{
    let c = *colors;
    let inner = row![
        label_desc(label, desc, colors),
        Space::new().width(Length::FillPortion(3)),
        pick_list(
            vec![TriState::Auto, TriState::True, TriState::False],
            Some(value),
            on_select,
        )
        .text_size(12)
        .width(90),
    ]
    .spacing(10)
    .align_y(iced::Alignment::Center);
    with_tip(inner, desc, c)
}

/// TriState row with an amber warning indicator — used for GPL which can break rendering.
fn tristate_row_warn<'a, F>(
    label: &str,
    desc: &str,
    value: TriState,
    on_select: F,
    colors: &ThemeColors,
) -> Element<'a, Message>
where
    F: 'a + Fn(TriState) -> Message,
{
    let c = *colors;
    let label_col: Element<Message> = column![
        row![
            text(String::from(label)).size(15).color(c.text),
            Space::new().width(4),
            container(text("\u{26A0}").size(13).color(c.warn)).padding([0, 0]),
        ]
        .align_y(iced::Alignment::Center),
        text(String::from(desc)).size(14).color(c.warn),
    ]
    .spacing(1)
    .width(Length::FillPortion(7))
    .into();

    let inner = row![
        label_col,
        Space::new().width(Length::FillPortion(3)),
        pick_list(
            vec![TriState::Auto, TriState::True, TriState::False],
            Some(value),
            on_select,
        )
        .text_size(12)
        .width(90),
    ]
    .spacing(10)
    .align_y(iced::Alignment::Center);
    with_tip(inner, desc, c)
}

/// Generic pick_list row.
fn pick_row<'a, T, F>(
    label: &str,
    desc: &str,
    options: &'a [T],
    value: T,
    on_select: F,
    colors: &ThemeColors,
) -> Element<'a, Message>
where
    T: 'a + Clone + PartialEq + std::fmt::Display,
    F: 'a + Fn(T) -> Message,
{
    let c = *colors;
    let inner = row![
        label_desc(label, desc, colors),
        Space::new().width(Length::FillPortion(3)),
        pick_list(options, Some(value), on_select)
            .text_size(12)
            .width(150),
    ]
    .spacing(10)
    .align_y(iced::Alignment::Center);
    with_tip(inner, desc, c)
}

/// HUD row with a label, description, text input, and quick-preset buttons.
fn hud_row<'a>(value: &str, colors: &ThemeColors) -> Element<'a, Message> {
    let c = *colors;
    let desc = "On-screen performance overlay. Combine tokens: fps, memory, devinfo, pipelines. Leave empty to disable.";

    let preset_btn = |label: &'static str, preset: &'static str| {
        let c2 = c;
        button(text(label).size(10))
            .on_press(Message::SetDxvkField(DxvkField::Hud(preset.to_string())))
            .padding([3, 6])
            .style(move |_t, status| match status {
                button::Status::Hovered => theme::tab_button_hovered_style(&c2),
                _ => theme::tab_button_style(&c2),
            })
    };

    let inner = column![
        label_desc("HUD", desc, colors),
        row![
            text_input("e.g. fps,memory", value)
                .on_input(|s| Message::SetDxvkField(DxvkField::Hud(s)))
                .width(Length::Fill)
                .padding([5, 8]),
            preset_btn("fps", "fps"),
            preset_btn("fps+mem", "fps,memory"),
            preset_btn("full", "fps,memory,devinfo"),
            preset_btn("off", ""),
        ]
        .spacing(4)
        .align_y(iced::Alignment::Center),
    ]
    .spacing(4);

    with_tip(inner, desc, c)
}
